model_list:
  - model_name: openai/gpt-4o
    mishikallm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

vector_store_registry:
  - vector_store_name: "bedrock-mishikallm-website-knowledgebase"
    mishikallm_params:
      vector_store_id: "T37J8R4WTM"
      custom_llm_provider: "bedrock"
      vector_store_description: "Bedrock vector store for the Mishikallm website knowledgebase"
      vector_store_metadata:
        source: "https://www.mishikallm.com/docs"

general_settings:
  store_prompts_in_spend_logs: true