model_list:
  - model_name: fake-openai-endpoint
    mishikallm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

mishikallm_settings:
  cache: True
  cache_params:
    type: redis

