model_list:
  - model_name: fake-openai-endpoint
    mishikallm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/
  - model_name: claude-3-5-sonnet-20241022
    mishikallm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-special-alias
    mishikallm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-5-sonnet-20241022
    mishikallm_params:
      model: anthropic/claude-3-5-sonnet-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: claude-3-7-sonnet-20250219
    mishikallm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic/*
    mishikallm_params:
      model: anthropic/*
      api_key: os.environ/ANTHROPIC_API_KEY
general_settings: 
  master_key: sk-1234 
  custom_auth: custom_auth_basic.user_api_key_auth