model_list:
  - model_name: fake-openai-endpoint
    mishikallm_params:
      model: openai/fake
      api_key: fake-key
      api_base: https://exampleopenaiendpoint-production.up.railway.app/

general_settings:
  use_redis_transaction_buffer: true

mishikallm_settings:
  cache: True
  cache_params:
    type: redis
    supported_call_types: []